---
# Only rubys, java, nodejs; all the services including postgresql except mysql.
deployment:
  name: "intalio_runtime"
dea:
  runtimes:
    - ruby18
    - ruby19
    - java
    - nodejs
jobs:
  install:
    - nats_server
    - cloud_controller:
        builtin_services:
          - redis
          - mongodb
          - postgresql
          - mysql
    - router
    - health_manager
    - ccdb
    - redis:
        index: "0"
    - redis_gateway
    - mongodb:
        index: "0"
    - mongodb_gateway
    - postgresql:
        index: "0"
    - postgresql_gateway
