---
# Only rubys, java, nodejs; all the services including postgresql except mysql.
#force postgresql to 127.0.0.1: this is a Micro-CF and the IP keeps changing.
deployment:
  name: "intalio_devbox"
  domain: "intalio.local"
  etc_issue_msg: "Welcome to Intalio Micro-Cloudfoundry"
nginx:
  client_max_body_size: 512M
  proxy_connect_timeout: 40
  proxy_send_timeout: 480
  proxy_read_timeout: 480
dea:
  runtimes:
    - ruby18
    - ruby19
    - java
    - nodejs
jobs:
  install:
    - cloudfoundry:
        vmc:
          version: 0.3.14.beta.4
    - nats_server:
        port: 4222
        user: nats
        password: nats  #override this
        tracked_net_iface: eth0
    - stager:
        max_staging_duration: 360
    - cloud_controller:
        admins: [ hmalphettes@intalio.com ]
        description: "Intalio CF"
        support_address: "http://support.intalio.com"
        app_uris:
          { allow_external: true }
        local_register_only: false
        builtin_services:
          - redis
          - mongodb
          - postgresql
        default_account_capacity:
          memory:   8192
          app_uris: 32
          services: 32
          apps:     32
        stager:
          max_staging_runtime: 360
    - router
    - health_manager
    - ccdb: #127.0.0.1 is good for a micro-cloud setup. otherwise comment out and let the IP
        host: 127.0.0.1
    - dea: #The max amount of memory available to run the apps.
        max_memory: 8192
    - redis_node:
        index: "0"
    - redis_gateway
    - mongodb_node:
        index: "0"
        available_memory: 8192
        max_memory: 5128
        version: 2.0.0
        node_timeout: 8 #2 is the default but we keep getting timeout issues.
        mongod_conf:
          journal: false
          noprealloc: true
          quota: true
          quotafiles: 8
          smallfiles: false
    - mongodb_gateway
    - postgresql_node:
        version: "9.0"
        index: "0"
        max_db_size: 5128 #each db max
        available_storage: 65536 #65G max of total DBs on this node
        max_db_conns: 50
        max_long_query: 360
        max_long_tx: 480
        listen_addresses: * #listen to any addresses
        local_acl: trust #trust local connections on psql for admin jobs
        pg_hba_extra: #an extra access rule line: free for all for now
          user: all
          database: all
          ip_and_mask: "0.0.0.0/0"
          pass_encrypt: md5
        server_root_user: vcap
        server_root_password: vcap
        extensions_in_template1: "ltree,uuid-ossp"
        node_timeout: 8
    - postgresql_gateway
    - monit:
        daemon_startup: 1
        vcap_components:
           - cloud_controller
           - dea
           - health_manager
           - mongodb_gateway
           - mongodb_node
           - postgresql_gateway
           - postgresql_node
           - redis_gateway
           - redis_node
           - router
        vcap_daemons:
           - nats_server
        others:
           - postgresql
