---
# Only rubys, java, nodejs; all the services including postgresql except mysql.
#force postgresql to 127.0.0.1: this is a Micro-CF and the IP keeps changing.
deployment:
  name: "intalio_runtime"
 #WARNING: unless you are installing on your laptop
 #you must change this.
  domain: "api.vcap.me"
nginx:
  client_max_body_size: 512M
  proxy_connect_timeout: 30
  proxy_send_timeout: 240
  proxy_read_timeout: 240
dea:
  runtimes:
    - ruby18
    - ruby19
    - java
    - nodejs
jobs:
  install:
    - nats_server:
        pidfile: "/var/vcap/sys/nats_server.pid"
        logfile: "/var/log/nats_server.log"
        port: 4222
        user: nats
        password: nats  #override this
    - cloud_controller:
        builtin_services:
          - redis
          - mongodb
          - postgresql
    - router
    - health_manager
    - ccdb: #127.0.0.1 is good for a micro-cloud setup. otherwise comment out and let the IP
        host: 127.0.0.1 
    - dea: #The max amount of memory an account can use.
        max_memory: 8192
    - redis:
        index: "0"
    - redis_gateway
    - mongodb:
        index: "0"
        available_memory: 8192
        max_memory: 5128
        version: 2.0.0
        node_timeout: 8 #2 is the default but we keep getting timeout issues.
    - mongodb_gateway
    - postgresql:
        index: "0"
        max_db_size: 5128 #each db max
        available_storage: 65536 #65G max of total DBs on this node
        max_db_conns: 50
        listen_addresses: "*"
        server_root_user: vcap
        server_root_password: vcap
        ltree_in_template1: true #true to import the ltree.sql file in the template1
        node_timeout: 8 #2 seconds is the default but we keep getting timeout errors. maybe this will help.
    - postgresql_gateway
